package com.routehub.pos.models

data class Property(
    val flatCount: Int = 0,
    val status: Int = 1,
    val units: Int? = null,
    val _id: String? = null,
    val qrCode: String? = null,
    val zoneId: Zone? = null,
    val wardId: Ward? = null,
    val propertyTypeId: PropertyType? = null,
    val propertyCategoryId: PropertyCategory? = null,
    val propertyUsageTypeId: PropertyUsageType? = null,
    val address1: String? = null,
    val projectId: String?  = null,
//    val userId: User? = null,
    val phoneVerificationToken: String? = null,
//    val mobileNumbers: List<String>? = null,
    val renters: List<String>? = null,
    val additionalData: List<String>? = null,
    val requestedChanges: List<String>? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val consumerId: String? = null,
    val name: String? = null,
    val ownerName: String? = null,
    val mobileNo: String? = null,
)